pipeline {
    agent any

    stages {

        stage('build') {
            steps {
            sh '''
                cd ./inventory-service
                ./mvnw -DskipTests clean compile
            '''
            }
        }

        stage('test') {
            steps {
            sh '''
                cd inventory-service
                    ./mvnw test
            '''
            }
        }

        stage('deliver') {
            steps {
            sh '''
                cd inventory-service
                    ./mvnw -DskipTests install
            '''
            }
        }

    }
}